repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: uv run ruff check --fix
        language: system
        types_or: [python, jupyter]
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types_or: [python, jupyter]
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
          - --preserve-cell-outputs
          - --
